import type { DiscoveryCard, DiscoveryTier } from "./cardTypes";

const iconFileById: Record<string, string> = {
  powerful: "powerful.png",
  impactful: "impactful.png",
  shimmering: "shimmering.png",
  tinny: "tinny.png",
  spitty: "spitty.png",
  metallic: "metallic.png",
  aggressive: "aggressive.png",
  sharp: "sharp.png",
  crisp: "crisp.png",
  scooped: "scooped.png",
  distant: "distant.png",
  lean: "lean.png",
  empty: "empty.png",
  faded: "faded.png",
  full: "full.png",
  thick: "thick.png",
  bassy: "bassy.png",
  vivid: "vivid.png",
  bloated: "bloated.png",
  muffled: "muffled.png",
  mellow: "mellow.png",
  chesty: "chesty.png",
  cupped: "cupped.png",
  pinched: "pinched.png",
  tubular: "tubular.png",
  brassy: "brassy.png",
  reedy: "reedy.png",
  cloudy: "cloudy.png",
  canned: "canned.png",
  brittle: "brittle.png",
  cold: "cold.png",
  woolly: "woolly.png",
  fatiguing: "fatiguing.png",
  veiled: "veiled.png",
  energetic: "energetic.png",
  vintage: "vintage.png",
  plasticky: "plasticky.png",
  congested: "congested.png",
  exciting: "exciting.png",
  piercing: "piercing.png",
  buried: "buried.png",
  precise: "precise.png",
  diffuse: "diffuse.png",
  intimate: "intimate.png",
  set_back: "set-back.png",
  spacious: "spacious.png",
  sluggish: "sluggish.png",
  surging: "surging.png",
  overdriven: "overdriven.png"
};

const discovery = (
  id: string,
  tier: DiscoveryTier,
  ingredientIds: string[],
  priority: number
): DiscoveryCard => ({
  id,
  role: "discovery",
  tier,
  ingredientIds,
  priority,
  icon: {
    src: `/icons/discoveries/${iconFileById[id]}`,
    altKey: `recipe.${id}.alt`
  },
  unlock: {
    hintLevel: "family_hint",
    playableAfterUnlock: true
  },
  textKeys: {
    label: `recipe.${id}.label`,
    explanation: `recipe.${id}.explanation`,
    hint: `recipe.${id}.hint`
  }
});

export const discoveryCards: DiscoveryCard[] = [
  discovery("powerful", "combo", ["rumble", "thump"], 70),
  discovery("impactful", "combo", ["thump", "punchy"], 70),
  discovery("shimmering", "combo", ["bright", "airy"], 70),
  discovery("tinny", "combo", ["thin", "harsh"], 70),
  discovery("spitty", "combo", ["thin", "sibilant"], 70),
  discovery("metallic", "combo", ["harsh", "glassy"], 75),
  discovery("aggressive", "combo", ["shouty", "harsh"], 75),
  discovery("sharp", "combo", ["bright", "harsh"], 70),
  discovery("crisp", "combo", ["bright", "glassy"], 70),
  discovery("scooped", "combo", ["hollow", "airy"], 75),
  discovery("distant", "combo", ["hollow", "dull"], 70),
  discovery("lean", "combo", ["thin", "bright"], 70),
  discovery("empty", "combo", ["thin", "hollow"], 75),
  discovery("faded", "combo", ["thin", "dull"], 70),
  discovery("full", "combo", ["warm", "bright"], 70),
  discovery("thick", "combo", ["warm", "boomy"], 70),
  discovery("bassy", "combo", ["boomy", "boxy"], 70),
  discovery("vivid", "combo", ["boomy", "bright"], 70),
  discovery("bloated", "combo", ["boomy", "muddy"], 70),
  discovery("muffled", "combo", ["muddy", "dull"], 70),
  discovery("mellow", "combo", ["warm", "dull"], 60),
  discovery("chesty", "combo", ["warm", "boxy"], 70),
  discovery("cupped", "combo", ["boxy", "honky"], 75),
  discovery("pinched", "combo", ["honky", "nasal"], 75),
  discovery("tubular", "combo", ["boxy", "nasal"], 70),
  discovery("brassy", "combo", ["nasal", "harsh"], 75),
  discovery("cloudy", "combo", ["muddy", "boxy"], 75),
  discovery("canned", "big_combo", ["boxy", "honky", "nasal"], 100),
  discovery("reedy", "big_combo", ["boxy", "nasal", "harsh"], 95),
  discovery("brittle", "big_combo", ["thin", "bright", "sibilant"], 90),
  discovery("cold", "big_combo", ["thin", "hollow", "airy"], 95),
  discovery("woolly", "big_combo", ["boomy", "muddy", "dull"], 90),
  discovery("fatiguing", "big_combo", ["shouty", "harsh", "sibilant"], 95),
  discovery("veiled", "big_combo", ["muddy", "boxy", "dull"], 90),
  discovery("energetic", "big_combo", ["rumble", "thump", "bright"], 80),
  discovery("vintage", "big_combo", ["warm", "boxy", "dull"], 80),
  discovery("plasticky", "mega_combo", ["thin", "hollow", "harsh", "glassy"], 120),
  discovery("congested", "mega_combo", ["muddy", "boxy", "honky", "dull"], 120),
  discovery("exciting", "mega_combo", ["rumble", "thump", "bright", "airy"], 110),
  discovery("piercing", "mega_combo", ["thin", "hollow", "shouty", "harsh", "sibilant"], 130),
  discovery("buried", "mega_combo", ["boomy", "muddy", "boxy", "honky", "dull"], 130),
  discovery("precise", "combo", ["centered", "focused"], 70),
  discovery("diffuse", "combo", ["wide", "blurred"], 70),
  discovery("intimate", "combo", ["near", "dry"], 70),
  discovery("set_back", "combo", ["far", "reverberant"], 70),
  discovery("spacious", "combo", ["wide", "reverberant"], 70),
  discovery("sluggish", "combo", ["softened", "loose"], 70),
  discovery("surging", "combo", ["compressed", "pumping"], 70),
  discovery("overdriven", "combo", ["clipped", "distorted"], 70)
];

export const discoveryById = new Map(discoveryCards.map((recipe) => [recipe.id, recipe]));
